# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-20 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tool.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True)),
                ('status', models.CharField(max_length=32)),
                ('input_file', models.FileField(upload_to=tool.models.user_run_input_directory)),
                ('run_dir', models.FileField(upload_to='')),
                ('redis_id', models.CharField(max_length=255)),
                ('job_queue', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='JobParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addgenes', models.BooleanField(default=False)),
                ('addmrna', models.BooleanField(default=False)),
                ('locustag', models.CharField(blank=True, max_length=32, null=True)),
                ('increment', models.CharField(blank=True, max_length=32, null=True)),
                ('gffver', models.CharField(blank=True, max_length=32, null=True)),
                ('compliant', models.BooleanField(default=False)),
                ('centre', models.CharField(blank=True, max_length=32, null=True)),
                ('accver', models.CharField(blank=True, max_length=32, null=True)),
                ('genus', models.CharField(blank=True, max_length=32, null=True)),
                ('species', models.CharField(blank=True, max_length=32, null=True)),
                ('strain', models.CharField(blank=True, max_length=32, null=True)),
                ('plasmid', models.CharField(blank=True, max_length=32, null=True)),
                ('kingdom', models.CharField(blank=True, max_length=32, null=True)),
                ('gcode', models.CharField(blank=True, max_length=32, null=True)),
                ('gram', models.CharField(blank=True, max_length=32, null=True)),
                ('usegenus', models.BooleanField(default=False)),
                ('proteins', models.CharField(blank=True, max_length=32, null=True)),
                ('hmms', models.CharField(blank=True, max_length=32, null=True)),
                ('metagenome', models.BooleanField(default=False)),
                ('rawproduct', models.BooleanField(default=False)),
                ('cdsrnaolap', models.BooleanField(default=False)),
                ('fast', models.BooleanField(default=False)),
                ('noanno', models.BooleanField(default=False)),
                ('mincontig_length', models.CharField(blank=True, max_length=32, null=True)),
                ('evalue', models.CharField(blank=True, max_length=32, null=True)),
                ('rfam', models.CharField(blank=True, max_length=32, null=True)),
                ('norrna', models.BooleanField(default=False)),
                ('notrna', models.BooleanField(default=False)),
                ('rnammer', models.BooleanField(default=False)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tool.Job')),
            ],
        ),
    ]
