# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-20 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_job_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
